# -*- coding: utf-8 -*-
"""2D_plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTqvTmRCf2PMq7wUoYtIHx7Nd-NTbNhb
"""

import pandas as pd
import matplotlib.pyplot as plt

def get_trend_w_categorical(x, categories, trend_name, index_map, mapping):

    x_mapped = x.map(index_map)
    categories_renamed = categories.rename(columns=mapping)
    categories_numeric = categories_renamed.apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)
    valid_mask = x_mapped.notna()
    x_filtered = x_mapped[valid_mask]
    categories_filtered = categories_numeric[valid_mask.values]
    grouped = categories_filtered.groupby(x_filtered).sum()
    grouped.index.name = trend_name
    return grouped

def plot_2d_trend(df, title):

    if df.shape[1] != 1:
        raise ValueError("Input DataFrame must have exactly one column.")

    plt.figure(figsize=(10, 6))
    markerline, stemlines, baseline = plt.stem(df.index, df.iloc[:, 0], linefmt='-', markerfmt='o', basefmt=" ")
    plt.setp(stemlines, 'linewidth', 1.5)
    plt.xlabel(df.index.name if df.index.name else "Index")
    plt.ylabel(df.columns[0])
    plt.title(title)
    plt.xticks(rotation=45)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    return df

# Main program
# file_path = "data/mobile_app_user_dataset_standardCurrency3.xlsx"
# df = pd.read_excel(file_path)
df = pd.read_excel(r"D:\UCSD Stuff\WI25\ECE 143\project\App-Usage-Survey\mobile_app_user_dataset.xlsx")

trend = 'Q19'
type_apps = [f'Q15_{i}' for i in range(1, 24)]

index_map = {
    1: 'American', 2: 'Australian', 3: 'Brazillian', 4: 'British', 5: 'Canadian',
    6: 'Chinese', 7: 'French', 8: 'German', 9: 'Indian', 10: 'Italian',
    11: 'Japanese', 12: 'Mexican', 13: 'Russian', 14: 'South Korean', 15: 'Spanish', 16: 'Other'
}

mapping = {
    'Q15_1': 'Navigation', 'Q15_2': 'Business', 'Q15_3': 'Catalogues', 'Q15_4': 'Travel',
    'Q15_5': 'Books', 'Q15_6': 'Photo & Video', 'Q15_7': 'Lifestyle', 'Q15_8': 'Entertainment',
    'Q15_9': 'Finance', 'Q15_10': 'News', 'Q15_11': 'Health & Fitness', 'Q15_12': 'Games',
    'Q15_13': 'Food & Drink', 'Q15_14': 'Education', 'Q15_15': 'Medical', 'Q15_16': 'Social Networking',
    'Q15_17': 'Reference', 'Q15_18': 'Sports', 'Q15_19': 'Utilities', 'Q15_20': 'Weather',
    'Q15_21': 'Productivity', 'Q15_22': 'Music', 'Q15_23': 'Other'
}

x = df[trend]
categories = df[type_apps]

trend_df = get_trend_w_categorical(x, categories, "Nationality", index_map, mapping)

if "Travel" in trend_df.columns:
    travel_df = trend_df[['Travel']].copy()
    travel_df.index.name = "Nationality"
    plot_2d_trend(travel_df, "Download Trend for Travel Apps by Nationality")
    print(travel_df)
else:
    print("'Travel' category not found.")